name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.5.5'
          projectPath: '$'
          args: '-noSplash -retry=0 -browserType=Chrome -testSuiteCollectionPath="Test Suites/Shopping-cart-tests - Run All Test Suites" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'